artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/13-suraj/Project-Datasets/raw/refs/heads/main/Face-Images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/perpare_base_model
  base_model_path: artifacts/perpare_base_model/base_model.keras
  updated_base_model_path: artifacts/perpare_base_model/base_model_updated.keras